Repository the-nexim/design-system, pull requests merged in 2025-01, with the labels that each got.

#6 refactor(snackbar): pass function for action handler
  .gitignore
  packages/snackbar/README.md
  packages/snackbar/src/lib/element.ts
  packages/snackbar/src/lib/handler.ts
  packages/snackbar/src/lib/signal.ts
  packages/snackbar/src/lib/type.ts
  packages/snackbar/src/main.ts
Labels: refactor, bugfix

#7 fix(snackbar): review and fix issues
  packages/snackbar/package.json
  packages/snackbar/src/lib/element.ts
  packages/snackbar/src/lib/handler.ts
  packages/snackbar/src/lib/type.ts
  packages/snackbar/src/lib/utils.ts
  yarn.lock
Labels: bugfix

#9 refactor: update output paths in package.json
  packages/snackbar/package.json
Labels: bugfix

#10 fix(snackbar): add styles for SnackbarElement component
  packages/snackbar/package.json
  packages/snackbar/style/main.css
Labels: bugfix

#15 feat(icons): create icon package for using google font icons
  packages/icon/LICENSE
  packages/icon/README.md
  packages/icon/package.json
  packages/icon/style/main.css
  yarn.lock
Labels: new-feature
